import { Event, ScheduledPost, Message, MessageTemplate, Notification } from '../types';

// Mock Events Data
export const mockEvents: Event[] = [
  {
    eventId: 'event-1',
    userId: 'mock-user-123',
    title: 'React Meetup: Advanced Hooks',
    description: 'Deep dive into React hooks and custom hook patterns',
    dateTime: new Date('2024-02-15T18:00:00'),
    location: 'Tech Hub, Downtown',
    meetupEventId: 'meetup-123',
    meetupEventStatus: 'published',
    linkedinEventId: 'linkedin-456',
    linkedinEventStatus: 'published',
    platformStatus: 'confirmed',
    source: 'platform',
    requiresConfirmation: false,
    publishToMeetup: true,
    publishToLinkedIn: true,
    socialPostsScheduled: true,
    messagesScheduled: true,
    lastSyncTime: new Date(),
    externallyModified: false,
    createdAt: new Date('2024-01-15T10:00:00'),
    updatedAt: new Date('2024-01-15T10:00:00'),
  },
  {
    eventId: 'event-2',
    userId: 'mock-user-123',
    title: 'TypeScript Workshop',
    description: 'Learn TypeScript fundamentals and best practices',
    dateTime: new Date('2024-03-01T14:00:00'),
    location: 'Online',
    meetupEventId: 'meetup-124',
    meetupEventStatus: 'draft',
    platformStatus: 'pending_confirmation',
    source: 'platform',
    requiresConfirmation: true,
    publishToMeetup: true,
    publishToLinkedIn: false,
    socialPostsScheduled: false,
    messagesScheduled: false,
    lastSyncTime: new Date(),
    externallyModified: false,
    createdAt: new Date('2024-01-20T15:30:00'),
    updatedAt: new Date('2024-01-20T15:30:00'),
  },
  {
    eventId: 'event-3',
    userId: 'mock-user-123',
    title: 'Node.js Performance Optimization',
    description: 'Techniques for optimizing Node.js applications for production',
    dateTime: new Date('2024-03-15T19:00:00'),
    location: 'Innovation Center, Midtown',
    meetupEventId: 'meetup-125',
    meetupEventStatus: 'published',
    linkedinEventId: 'linkedin-457',
    linkedinEventStatus: 'published',
    platformStatus: 'confirmed',
    source: 'platform',
    requiresConfirmation: false,
    publishToMeetup: true,
    publishToLinkedIn: true,
    socialPostsScheduled: true,
    messagesScheduled: true,
    lastSyncTime: new Date(),
    externallyModified: false,
    createdAt: new Date('2024-02-01T09:00:00'),
    updatedAt: new Date('2024-02-01T09:00:00'),
  },
  {
    eventId: 'event-4',
    userId: 'mock-user-123',
    title: 'GraphQL API Design',
    description: 'Building scalable GraphQL APIs with best practices',
    dateTime: new Date('2024-04-05T17:30:00'),
    location: 'Startup Hub, East Side',
    meetupEventId: 'meetup-126',
    meetupEventStatus: 'published',
    platformStatus: 'confirmed',
    source: 'platform',
    requiresConfirmation: false,
    publishToMeetup: true,
    publishToLinkedIn: false,
    socialPostsScheduled: true,
    messagesScheduled: true,
    lastSyncTime: new Date(),
    externallyModified: false,
    createdAt: new Date('2024-02-10T14:00:00'),
    updatedAt: new Date('2024-02-10T14:00:00'),
  },
  {
    eventId: 'event-5',
    userId: 'mock-user-123',
    title: 'Docker & Kubernetes Workshop',
    description: 'Containerization and orchestration for modern applications',
    dateTime: new Date('2024-04-20T10:00:00'),
    location: 'DevOps Center, North District',
    meetupEventId: 'meetup-127',
    meetupEventStatus: 'draft',
    platformStatus: 'pending_confirmation',
    source: 'platform',
    requiresConfirmation: true,
    publishToMeetup: true,
    publishToLinkedIn: true,
    socialPostsScheduled: false,
    messagesScheduled: false,
    lastSyncTime: new Date(),
    externallyModified: false,
    createdAt: new Date('2024-02-15T11:30:00'),
    updatedAt: new Date('2024-02-15T11:30:00'),
  },
  {
    eventId: 'event-6',
    userId: 'mock-user-123',
    title: 'Web Security Fundamentals',
    description: 'Essential security practices for web developers',
    dateTime: new Date('2024-05-10T18:30:00'),
    location: 'Security Institute, Financial District',
    meetupEventId: 'meetup-128',
    meetupEventStatus: 'published',
    linkedinEventId: 'linkedin-458',
    linkedinEventStatus: 'published',
    platformStatus: 'confirmed',
    source: 'platform',
    requiresConfirmation: false,
    publishToMeetup: true,
    publishToLinkedIn: true,
    socialPostsScheduled: true,
    messagesScheduled: true,
    lastSyncTime: new Date(),
    externallyModified: false,
    createdAt: new Date('2024-03-01T16:00:00'),
    updatedAt: new Date('2024-03-01T16:00:00'),
  },
  {
    eventId: 'event-7',
    userId: 'mock-user-123',
    title: 'AI/ML for Web Developers',
    description: 'Introduction to machine learning concepts for web development',
    dateTime: new Date('2024-05-25T15:00:00'),
    location: 'AI Research Lab, University Campus',
    meetupEventId: 'meetup-129',
    meetupEventStatus: 'published',
    platformStatus: 'confirmed',
    source: 'meetup_import',
    requiresConfirmation: false,
    publishToMeetup: true,
    publishToLinkedIn: false,
    socialPostsScheduled: true,
    messagesScheduled: true,
    lastSyncTime: new Date(),
    externallyModified: true,
    createdAt: new Date('2024-03-10T12:00:00'),
    updatedAt: new Date('2024-03-12T09:30:00'),
  },
  {
    eventId: 'event-8',
    userId: 'mock-user-123',
    title: 'Mobile-First Design Principles',
    description: 'Creating responsive designs that work great on all devices',
    dateTime: new Date('2024-06-08T13:00:00'),
    location: 'Design Studio, Creative Quarter',
    meetupEventId: 'meetup-130',
    meetupEventStatus: 'cancelled',
    platformStatus: 'cancelled',
    source: 'platform',
    requiresConfirmation: false,
    publishToMeetup: true,
    publishToLinkedIn: true,
    socialPostsScheduled: false,
    messagesScheduled: false,
    lastSyncTime: new Date(),
    externallyModified: false,
    createdAt: new Date('2024-03-15T10:15:00'),
    updatedAt: new Date('2024-03-20T14:45:00'),
  },
];

// Mock Scheduled Posts Data
export const mockScheduledPosts: ScheduledPost[] = [
  {
    postId: 'post-1',
    eventId: 'event-1',
    userId: 'mock-user-123',
    platform: 'linkedin',
    content: 'Join us for an amazing React Meetup next month! 🚀 #React #JavaScript',
    scheduledTime: new Date('2024-01-15T09:00:00'),
    status: 'published',
    externalPostId: 'linkedin-post-123',
    requiresConfirmation: false,
    createdAt: new Date('2024-01-15T10:00:00'),
  },
  {
    postId: 'post-2',
    eventId: 'event-1',
    userId: 'mock-user-123',
    platform: 'linkedin',
    content: 'Only 2 weeks left to register for our React Meetup! 📅',
    scheduledTime: new Date('2024-02-01T09:00:00'),
    status: 'pending',
    requiresConfirmation: false,
    createdAt: new Date('2024-01-15T10:00:00'),
  },
];

// Mock Messages Data
export const mockMessages: Message[] = [
  {
    messageId: 'msg-1',
    eventId: 'event-1',
    userId: 'mock-user-123',
    recipientType: 'attendees',
    content: 'Thanks for registering for our React Meetup! Here are the event details and what to expect. We\'ll be covering advanced hooks patterns and best practices.',
    scheduledTime: new Date('2024-02-14T10:00:00'),
    status: 'sent',
    recipientCount: 25,
    sentCount: 25,
    requiresConfirmation: false,
    createdAt: new Date('2024-01-15T10:00:00'),
  },
  {
    messageId: 'msg-2',
    eventId: 'event-1',
    userId: 'mock-user-123',
    recipientType: 'non_rsvp_members',
    content: 'Don\'t miss out on our upcoming React meetup! Limited seats available.',
    scheduledTime: new Date('2024-02-10T14:00:00'),
    status: 'pending',
    recipientCount: 150,
    sentCount: 0,
    requiresConfirmation: false,
    createdAt: new Date('2024-01-15T10:00:00'),
  },
  {
    messageId: 'msg-3',
    eventId: 'event-2',
    userId: 'mock-user-123',
    recipientType: 'attendees',
    content: 'Welcome to the TypeScript Workshop! Please bring your laptop and make sure you have Node.js installed.',
    scheduledTime: new Date('2024-02-28T09:00:00'),
    status: 'sent',
    recipientCount: 18,
    sentCount: 18,
    requiresConfirmation: false,
    createdAt: new Date('2024-01-20T15:30:00'),
  },
  {
    messageId: 'msg-4',
    eventId: 'event-3',
    userId: 'mock-user-123',
    recipientType: 'attendees',
    content: 'Reminder: Node.js Performance Optimization workshop is tomorrow! We\'ll be diving deep into profiling and optimization techniques.',
    scheduledTime: new Date('2024-03-14T18:00:00'),
    status: 'sent',
    recipientCount: 32,
    sentCount: 32,
    requiresConfirmation: false,
    createdAt: new Date('2024-02-01T09:00:00'),
  },
  {
    messageId: 'msg-5',
    eventId: 'event-4',
    userId: 'mock-user-123',
    recipientType: 'non_rsvp_members',
    content: 'Join us for an exciting GraphQL API Design session! Learn how to build scalable APIs with modern best practices.',
    scheduledTime: new Date('2024-04-01T12:00:00'),
    status: 'pending',
    recipientCount: 200,
    sentCount: 0,
    requiresConfirmation: false,
    createdAt: new Date('2024-02-10T14:00:00'),
  },
  {
    messageId: 'msg-6',
    eventId: 'event-5',
    userId: 'mock-user-123',
    recipientType: 'attendees',
    content: 'Docker & Kubernetes Workshop preparation: Please install Docker Desktop before the event. We\'ll send setup instructions soon.',
    scheduledTime: new Date('2024-04-18T16:00:00'),
    status: 'failed',
    recipientCount: 15,
    sentCount: 0,
    errorMessage: 'SMTP server connection failed',
    requiresConfirmation: false,
    createdAt: new Date('2024-02-15T11:30:00'),
  },
  {
    messageId: 'msg-7',
    eventId: 'event-6',
    userId: 'mock-user-123',
    recipientType: 'attendees',
    content: 'Web Security Fundamentals - Important: This session will cover sensitive security topics. Please review our code of conduct.',
    scheduledTime: new Date('2024-05-08T10:00:00'),
    status: 'pending',
    recipientCount: 28,
    sentCount: 0,
    requiresConfirmation: true,
    createdAt: new Date('2024-03-01T16:00:00'),
  },
  {
    messageId: 'msg-8',
    eventId: 'event-7',
    userId: 'mock-user-123',
    recipientType: 'non_rsvp_members',
    content: 'Discover AI/ML for Web Developers! This beginner-friendly session will introduce machine learning concepts relevant to web development.',
    scheduledTime: new Date('2024-05-20T11:00:00'),
    status: 'sent',
    recipientCount: 180,
    sentCount: 175,
    requiresConfirmation: false,
    createdAt: new Date('2024-03-10T12:00:00'),
  },
];

// Mock Message Templates Data
export const mockMessageTemplates: MessageTemplate[] = [
  {
    templateId: 'template-1',
    name: 'Welcome Attendees',
    recipientType: 'attendees',
    content: 'Thanks for registering for {{eventTitle}}! We\'re excited to see you on {{eventDate}} at {{eventLocation}}. Please arrive 15 minutes early for check-in.',
    isDefault: true,
    createdAt: new Date('2024-01-01T00:00:00'),
    updatedAt: new Date('2024-01-01T00:00:00'),
  },
  {
    templateId: 'template-2',
    name: 'Invite Non-RSVPs',
    recipientType: 'non_rsvp_members',
    content: 'Hi there! We have an exciting event coming up: {{eventTitle}}. Join us on {{eventDate}} at {{eventLocation}}. Don\'t miss out!',
    isDefault: true,
    createdAt: new Date('2024-01-01T00:00:00'),
    updatedAt: new Date('2024-01-01T00:00:00'),
  },
  {
    templateId: 'template-3',
    name: 'Event Reminder',
    recipientType: 'attendees',
    content: 'Reminder: {{eventTitle}} is happening tomorrow at {{eventDate}}! We can\'t wait to see you at {{eventLocation}}.',
    isDefault: false,
    createdAt: new Date('2024-01-05T00:00:00'),
    updatedAt: new Date('2024-01-05T00:00:00'),
  },
  {
    templateId: 'template-4',
    name: 'Last Chance Invitation',
    recipientType: 'non_rsvp_members',
    content: 'Last chance to join {{eventTitle}}! Only a few spots left for {{eventDate}}. Register now to secure your place.',
    isDefault: false,
    createdAt: new Date('2024-01-10T00:00:00'),
    updatedAt: new Date('2024-01-10T00:00:00'),
  },
  {
    templateId: 'template-5',
    name: 'Pre-Event Setup',
    recipientType: 'attendees',
    content: 'Get ready for {{eventTitle}}! Please make sure you have the required software installed. Event details: {{eventDate}} at {{eventLocation}}.',
    isDefault: false,
    createdAt: new Date('2024-01-15T00:00:00'),
    updatedAt: new Date('2024-01-15T00:00:00'),
  },
  {
    templateId: 'template-6',
    name: 'Follow-up Thank You',
    recipientType: 'attendees',
    content: 'Thank you for attending {{eventTitle}}! We hope you enjoyed the session. Please share your feedback and stay tuned for future events.',
    isDefault: false,
    createdAt: new Date('2024-01-20T00:00:00'),
    updatedAt: new Date('2024-01-20T00:00:00'),
  },
];

// Mock Notifications Data
export const mockNotifications: Notification[] = [
  {
    notificationId: 'notif-1',
    userId: 'mock-user-123',
    type: 'success',
    title: 'Event Created Successfully',
    message: 'Your event "React Meetup: Advanced Hooks" has been created and published to Meetup.com and LinkedIn.',
    relatedEntityId: 'event-1',
    relatedEntityType: 'event',
    read: false,
    createdAt: new Date('2024-01-15T10:00:00'),
  },
  {
    notificationId: 'notif-2',
    userId: 'mock-user-123',
    type: 'warning',
    title: 'Draft Event Pending',
    message: 'Your event "TypeScript Workshop" is in draft mode and requires confirmation before publishing.',
    relatedEntityId: 'event-2',
    relatedEntityType: 'event',
    read: false,
    createdAt: new Date('2024-01-20T15:30:00'),
  },
  {
    notificationId: 'notif-3',
    userId: 'mock-user-123',
    type: 'info',
    title: 'Social Post Published',
    message: 'Your LinkedIn post for "React Meetup: Advanced Hooks" has been published successfully.',
    relatedEntityId: 'post-1',
    relatedEntityType: 'post',
    read: true,
    createdAt: new Date('2024-01-15T09:05:00'),
  },
];